update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b145-IorfpI8arxeX.png' where name = 'Sakura Haruno';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b17-phjcWCkRuIhu.png' where name = 'Naruto Uzumaki';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png' where name = 'Sasuke Uchiha';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b85-mkVBh2yjxjmx.png' where name = 'Kakashi Hatake';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png' where name = 'Itachi Uchiha';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b306-oUTOO45xInXt.png' where name = 'Rock Lee';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b1662-4E5J0LX9jZKZ.png' where name = 'Gaara';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b2767-r61Cj9v8I0wl.png' where name = 'Tsunade';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b2535-Xq9WKNPJQEt3.png' where name = 'Minato Namikaze';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b914-KuS8AWjqBrqa.jpg' where name = 'Piccolo';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b2093-kdFZhqcNSsqW.png' where name = 'Gohan';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b3694-bDfOdSSdFfPv.png' where name = 'Frieza';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b913-NIFkKazWM8VO.png' where name = 'Vegeta';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/246-wsRRr6z1kii8.png' where name = 'Goku';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b4014-of2ONLvA7T8p.jpg' where name = 'Yamcha';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b2707-YKWmn4q87oF8.png' where name = 'Future Trunks';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b4318-HfIy9rOIOZXM.png' where name = 'Android 18';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/3908.jpg' where name = 'Cell';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/1012.jpg' where name = 'Majin Buu';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b723-vp5hPptgnNEC.png' where name = 'Nami';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b305-6lisPmHtCnLT.png' where name = 'Sanji';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b2072-Lc6jEdsueJUK.jpg' where name = 'Portgas D. Ace';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b62-S7oAeA9WInjV.png' where name = 'Roronoa Zoro';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png' where name = 'Monkey D. Luffy';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b724-GFGgI9AJQkfy.jpg' where name = 'Usopp';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b61-ywXUyyocEEqt.png' where name = 'Nico Robin';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b13767-U604OJN9dxCn.jpg' where name = 'Trafalgar Law';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b16342-kVOF6V5Q94go.png' where name = 'Boa Hancock';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b3149-j6cl8A9yup51.png' where name = 'Obito Uchiha';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b46109-MT7Hm4Bk93In.png' where name = 'Kaido';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b46494-g7xYYuBtYPnO.png' where name = 'Armin Arlert';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b62481-ZZDa7vn17lMU.png' where name = 'Historia Reiss';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg' where name = 'Eren Yeager';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b40881-F3gr1PkreDvj.png' where name = 'Mikasa Ackerman';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b45627-CR68RyZmddGG.png' where name = 'Levi Ackerman';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/n46486-izhPjzut6WCZ.png' where name = 'Connie Springer';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b45887-QPtJH0KwqthW.jpg' where name = 'Sasha Blouse';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b46484-P6A2GjNQn49F.png' where name = 'Reiner Braun';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b125661-FiqFvAtNlL0v.png' where name = 'Zeke Yeager';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg' where name = 'Eren (Founding Titan)';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b89221-gSF2a4gPbG4m.png' where name = 'Ochaco Uraraka';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b89028-8w1I9o1ISHMg.png' where name = 'Izuku Midoriya';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b88892-bdOha3lNcaN6.png' where name = 'Katsuki Bakugo';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b89220-KNBwaVFAR8FD.png' where name = 'Shoto Todoroki';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b89224-K6KEuQAuYKzq.jpg' where name = 'All Might';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b89244-VVwK9loDHeTV.png' where name = 'Minoru Mineta';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b89243-QLmUyyZk5K2l.png' where name = 'Eijiro Kirishima';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b89241-Q8KzAfX4Qe2y.png' where name = 'Momo Yaoyorozu';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b128299-eMEsWazNXE56.png' where name = 'Hawks';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b89226-C1ZKm2U3bR4T.png' where name = 'Tomura Shigaraki';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b129131-FZrQ7lSlxmEr.png' where name = 'Zenitsu Agatsuma';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/n129130-SJC0Kn1DU39E.jpg' where name = 'Inosuke Hashibira';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b127518-NRlq1CQ1v1ro.png' where name = 'Nezuko Kamado';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png' where name = 'Tanjiro Kamado';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b129133-VlTPowwt68rJ.png' where name = 'Kyojuro Rengoku';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b137776-E0QuFD7y19OQ.jpg' where name = 'Genya Shinazugawa';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b136072-xVwyRUKdpybi.png' where name = 'Mitsuri Kanroji';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b137778-H4Uzb9cSCvZ6.jpg' where name = 'Gyomei Himejima';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b144591-v2yrXtHorZFS.png' where name = 'Doma';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b129132-4nIZakUZ1o8W.jpg' where name = 'Muzan Kibutsuji';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b835-CiZa8y2z2gCz.png' where name = 'Misa Amane';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/n464-6KeJpU6g7Hwj.jpg' where name = 'Near';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b75-IkEpzO21LgFy.jpg' where name = 'Ryuk';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png' where name = 'Light Yagami';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b71-1W4panC53vfs.png' where name = 'L Lawliet';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/n1906-JCWKEGGook3Z.png' where name = 'Matsuda';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b463-QBLeLf6XxVg6.png' where name = 'Mello';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/n2730-SNbfxShpg90k.png' where name = 'Matt';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/n1905-9GfCvLFKNRLR.png' where name = 'Rem';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png' where name = 'Light Yagami (Kira)';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/63-xloedtYxiJ2E.jpg' where name = 'Winry Rockbell';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b12-tCKu8yK5kFL5.jpg' where name = 'Alphonse Elric';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b11-TA5Nuk7EDUZG.jpg' where name = 'Edward Elric';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b66-bLbGWXrmDqfV.png' where name = 'Scar';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b68-moBLY2WO2am3.png' where name = 'Roy Mustang';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b69-MRetSG8Qevvu.png' where name = 'Maes Hughes';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b351-XMQzTuMy2Xtn.jpg' where name = 'Greed';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/n3934-MKTV6tQeP8T3.png' where name = 'Olivier Armstrong';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/10982.jpg' where name = 'Pride';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/n15542-7kL0vJ9U8bVR.png' where name = 'Father';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b29-RgzoSeKmDYzl.jpg' where name = 'Leorio Paradinight';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b28-ivA7UGnfE40a.png' where name = 'Kurapika';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b30-lyFExKyDhefc.jpg' where name = 'Gon Freecss';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b27-Z5O02kQUydpT.jpg' where name = 'Killua Zoldyck';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b31-FZckOuu7L1un.png' where name = 'Hisoka Morow';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b13898-nHq3fRmp9uPD.png' where name = 'Biscuit Krueger';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/3195.jpg' where name = 'Feitan';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b12300-kYzopQUTLa9A.png' where name = 'Neferpitou';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b57-pTFguojSOQZW.png' where name = 'Illumi Zoldyck';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b23277-EYmIxzL64Mji.png' where name = 'Meruem';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b36830-41SWIDvhqOo4.png' where name = 'Klein';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b55147-1fCU8lONEuZQ.png' where name = 'Sinon';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b36828-j5ib0adAzGMx.png' where name = 'Asuna';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b75450-vDO1lQup1pe7.jpg' where name = 'Alice';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b36765-BnLbXg0Tzzh9.png' where name = 'Kirito';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b36831-JfyFU7gPPVmr.png' where name = 'Leafa';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b70899-TwMq5mtH5ifc.jpg' where name = 'Eugeo';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b126740-BQk6zlwPE7Kn.png' where name = 'Bercouli';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b123199-lfDRm9MJrznY.png' where name = 'Cardinal';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b123195-s4QPQ0OkqaKa.png' where name = 'Administrator';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b133700-f6sOO3TcgLV6.png' where name = 'Nobara Kugisaki';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b134167-5TCytk45YByD.png' where name = 'Maki Zenin';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b126635-L0y3I92JSUkN.png' where name = 'Megumi Fushiguro';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b127212-FVm2tD0erQ5B.png' where name = 'Yuji Itadori';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png' where name = 'Satoru Gojo';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b157115-kdhRYQdVhH95.png' where name = 'Inumaki Toge';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b137975-6TH7PiLWJaqy.png' where name = 'Aoi Todo';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b133704-8wLTGjc234q2.png' where name = 'Kento Nanami';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b133701-rCQuDpHr3UZL.png' where name = 'Sukuna';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b133702-Y7JRG5vAvjIL.png' where name = 'Mahito';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b2161-DyKLTXn1hkcL.png' where name = 'Hanataro Yamada';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b6-25WoBeWMZXBc.png' where name = 'Rukia Kuchiki';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b906-ImRjx5HFM8X6.png' where name = 'Renji Abarai';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b907-kgnDKeMtEN5y.png' where name = 'Byakuya Kuchiki';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b5-a7bkJgjhhigE.png' where name = 'Ichigo Kurosaki';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b1080-JUNo2Or0UGZg.jpg' where name = 'Grimmjow Jaegerjaquez';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b1081-xLTqHfLL2I2W.png' where name = 'Ulquiorra Cifer';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b3212-F5qZe4NWlZq9.png' where name = 'Coyote Starrk';
update public.characters set image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b1086-qR9218BjZTC0.png' where name = 'Sosuke Aizen';
